name: SmallWarps
main: net.acomputerdog.smallwarps.PluginSmallWarps
version: 1.8.1
description: Adds simple home and spawn warps
author: acomputerdog

commands:
  home:
    description: Teleport to home bed
    permission: smallwarps.home
    usage: /home
    aliases: [swhome, swbed, bed]
  spawn:
    description: Teleport to world spawn
    permission: smallwarps.spawn
    usage: /spawn
    aliases: [swspawn, swworld, worldspawn]
  back:
    description: Return to previous warp point
    permission: smallwarps.back
    usage: /back
    aliases: [swback, swreturn, return]
  tpa:
    description: Request to TP to another player
    permission: smallwarps.spawn
    usage: /tpa <player>
    aliases: [swtpa, swtp]
  tpaccept:
    description: Accept a TP request
    usage: /tpaccept
    aliases: [swtpaccept, swaccept, tpal]
  tpdeny:
    description: Denys a TP request
    usage: /tpdeny
    aliases: [swtpdeny, swdeny, tpd]
  tpcancel:
    description: Cancels a TP request
    usage: /tpcancel
    aliases: [swtpcancel, swcancel, tpc]
  warp:
    description: TPs to an admin warp
    permission: smallwarps.warp.use
    usage: /warp <name>
    aliases: swwarp
  mkwarp:
    description: Creates or edits an admin warp
    permission: smallwarps.warp.edit
    usage: /mkwarp <name> [<world> <x> <y> <z>]
    aliases: [swmkwarp, makewarp, swmakewarp]
  rmwarp:
    description: Removes an admin warp
    permission: smallwarps.warp.edit
    usage: /rmwarp <name>
    aliases: [swrmwarp, removewarp, swremovewarp]
  lswarp:
    description: Lists admin warps
    permission: smallwarps.warp.list
    usage: /lswarp
    aliases: [swlswarp, listwarp, swlistwarp, lswarps, swlswarps, listwarps, swlistwarps]
  swreload:
    description: Reload the plugin
    permission: smallwarps.reload
    usage: /swreload
  tp:
    description: Uses normal /tp but records player position for /back
    permission: smallwarps.tp.use
    usage: /tp <args>
    aliases: [swtp, teleport, swteleport]

permissions:
  smallwarps.home:
    description: Use /home
    default: true
  smallwarps.spawn:
    description: Use /spawn
    default: true
  smallwarps.back:
    description: Use /back
    default: true
  smallwarps.tpa:
    description: Use /tpa, /tpaccept, /tpdeny, and /tpcancel
    default: true
  smallwarps.warp.use:
    description: Use /warp
    default: op
  smallwarps.warp.edit:
    description: Use /mkwarp and /rmwarp
    default: op
  smallwarps.warp.list:
    description: Use /lswarp
    default: op
  smallwarps.reload:
    description: Use /swreload
    default: op
  smallwarps.tp.force:
    description: Force user to be able to access /tp
    default: false
  smallwarps.tp.use:
    description: Allow use of /tp (if vanilla permissions apply)
    default: true